const NETSCAPE_HEADER = [
    "# Netscape HTTP Cookie File",
    "# https://curl.se/docs/http-cookies.html",
    "# Generated by CookieKit. Cookies can grant access to your accounts.",
    "# SameSite and partition information cannot be represented in this format."
];

const UNSAFE_FIELD_CHARACTERS = /[\t\r\n]/;

function stringField(value) {
    return typeof value === "string" ? value : "";
}

function isSafeField(value) {
    return !UNSAFE_FIELD_CHARACTERS.test(value);
}

function expirationField(expirationDate) {
    if (!Number.isFinite(expirationDate) || expirationDate <= 0) {
        return "0";
    }

    return String(Math.floor(expirationDate));
}

function sortableCookie(cookie, index) {
    const normalizedCookie = cookie && typeof cookie === "object" ? cookie : {};

    return {
        cookie: normalizedCookie,
        index,
        domain: stringField(normalizedCookie.domain),
        path: stringField(normalizedCookie.path) || "/",
        name: stringField(normalizedCookie.name)
    };
}

function compareStrings(left, right) {
    if (left === right) {
        return 0;
    }

    return left < right ? -1 : 1;
}

function compareCookies(left, right) {
    const domainComparison = compareStrings(left.domain, right.domain);
    if (domainComparison !== 0) {
        return domainComparison;
    }

    const pathComparison = compareStrings(left.path, right.path);
    if (pathComparison !== 0) {
        return pathComparison;
    }

    const nameComparison = compareStrings(left.name, right.name);
    if (nameComparison !== 0) {
        return nameComparison;
    }

    return left.index - right.index;
}

function serializeCookie(cookie) {
    const rawDomain = stringField(cookie.domain);
    const path = stringField(cookie.path) || "/";
    const name = stringField(cookie.name);
    const value = stringField(cookie.value);

    if (!rawDomain || ![rawDomain, path, name, value].every(isSafeField)) {
        return null;
    }

    const domain = cookie.httpOnly ? `#HttpOnly_${rawDomain}` : rawDomain;
    const fields = [
        domain,
        cookie.hostOnly ? "FALSE" : "TRUE",
        path,
        cookie.secure ? "TRUE" : "FALSE",
        expirationField(cookie.expirationDate),
        name,
        value
    ];

    return fields.join("\t");
}

function sanitizedHostname(hostname) {
    const sanitized = stringField(hostname)
        .toLowerCase()
        .replace(/[^a-z0-9.-]+/g, "-")
        .replace(/^[.-]+|[.-]+$/g, "")
        .replace(/-{2,}/g, "-");

    return sanitized || "site";
}

function timestampForFilename(date) {
    return date
        .toISOString()
        .replace(/[-:]/g, "")
        .replace(/\.\d{3}Z$/, "Z");
}

export function createNetscapeExport(cookies, hostname, generatedAt = new Date()) {
    const date = generatedAt instanceof Date ? generatedAt : new Date(generatedAt);
    if (Number.isNaN(date.getTime())) {
        throw new TypeError("generatedAt must be a valid date");
    }

    const sortedCookies = Array.isArray(cookies)
        ? cookies.map(sortableCookie).sort(compareCookies)
        : [];
    const lines = [];
    let omittedCount = 0;

    for (const {cookie} of sortedCookies) {
        const line = serializeCookie(cookie);
        if (line === null) {
            omittedCount += 1;
            continue;
        }

        lines.push(line);
    }

    const header = [
        ...NETSCAPE_HEADER,
        `# Generated at ${date.toISOString()}`,
        ""
    ];

    return {
        contents: [...header, ...lines, ""].join("\n"),
        filename: `cookies-${sanitizedHostname(hostname)}-${timestampForFilename(date)}.txt`,
        exportedCount: lines.length,
        omittedCount
    };
}

export function selectCookieStore(stores, tabId) {
    if (!Array.isArray(stores) || tabId === undefined || tabId === null) {
        return null;
    }

    return stores.find((store) => (
        Array.isArray(store.tabIds) && store.tabIds.includes(tabId)
    )) ?? null;
}
